### ISSUE TITLE
web/index.php a template

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-websanlexicon#10]
xxx/web/index,php is sort of 'home page' for dictionary xxx: 

![image](https://user-images.githubusercontent.com/6393033/68261862-5f346480-000f-11ea-8afe-ec9076d3e0d8.png)

Previously, copies of this were kept as csl-websanlexicon/v02/distinctfiles/xxx/web/index.php.

Now, these distinctfile copies have been replaced by a template: [index.php](https://github.com/sanskrit-lexicon/csl-websanlexicon/blob/master/v02/makotemplates/web/index.php).

This required introduction of two additional [dictionary parameters](https://github.com/sanskrit-lexicon/csl-websanlexicon/blob/master/v02/dictparms.py):
* dictwc : For the worldcat link
* dictbe : For the bibliographic entry

The distinctfile copies were deleted.

**Comment by gasyoun** [comment]
> The distinctfile copies were deleted.

Thanks.

There is another aspect I've been thinking long about. Should not `Front Matter` be part of Available displays? Without reading the Preface most dictionaries are used wrongly, but locating it now might become pain. It's not just related, it's crucial.

**Comment by funderburkjim** [comment]
> Front Matter

We do have the front matter in a repository:  https://github.com/sanskrit-lexicon/csl-doc
Similarly for the home page:  https://github.com/sanskrit-lexicon/csl-homepage

So we are *part of the way* towards what I think you have in mind.

Currently these only work in the context of the Cologne server.
There needs to be a little tweaking so that they can function in the context of a local (non-cologne) installation.   And then documentation needs to be amended to describe how these repositories can be made an optional part of a local installation.

**Comment by funderburkjim** [comment]
There is now a local installation for a homepage: see https://github.com/sanskrit-lexicon/csl-homepage/issues/2

The csl-doc repository (which has the 'front matter') also can be installed locally: see https://github.com/sanskrit-lexicon/csl-doc/issues/4.

The link to csl-doc from the local homepage  go to the local csl-doc.

**Comment by drdhaval2785** [comment]
As both local and cologne setups are now done, closing this.
