### ISSUE TITLE
Code refactor

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-websanlexicon#13]
Substantial refactoring of code starting with getword.php.  The objectives: 
* to make the code closer to that for getword in csl-apidev repository.
* to make the code less 'spaghetti-like'.

Also simplified the Advanced Search code.

The refactoring is not yet completed, and has not been installed at Cologne.

I'll continue the work when I return; but for now the revisions are safe in Github.

**Comment by gasyoun** [comment]
> Also simplified the Advanced Search code.

Sounds promising.

**Comment by funderburkjim** [comment]
Have installed the refactor at Cologne.   
It currently has an impact only on MW,  and only for the Basic and Advanced Search,

**Comment by drdhaval2785** [comment]
Any plans for applying it to any other dictionaries @funderburkjim ?

**Comment by funderburkjim** [comment]
Yes, this has been applied to all dictionaries.

The code base for generating html  in csl-apidev (for simple-search, etc.)  is now quite similar to
the code base in csl-websanlexicon (for Basic, Advanced, .. displays) .

There is still room for making this common code easier to understand, and therefore easier to enhance or correct.

But that will be another day.  Can close this issue.
