### ISSUE TITLE
IAST and Devanagari input choices

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-websanlexicon#14]
There  currently are 'Devanagari' and IAST (Roman) input spelling options within
displays using the csl-apidev code; for instance the 'simple-search' url (https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/simple-search/v1.0/list-0.2s.html)  has these two input options.

These same two options are now available for the Basic, Advanced Search, and Mobile1 displays.

Currently, I've only installed this into these displays for MW dictionary.   I hope users will give these a try, to see if any bugs are uncovered when using Roman or Devanagari input.

**Comment by funderburkjim** [comment]
Reason:  A good case for this enhancement came up during the course of several emails with a long-time user, Dominic W.

Here are the gists of the discussion:

### Dominic
```
Eight years ago (!) you kindly explained to me how to cite a particular lookup result.  
But with the newer incarnations of the dictionary, the results now complain and 
recommend using the newer MW.  But the syntax you gave formerly doesn't quite 
work.  I've tried some variants, but without luck.  Can you tell me the current 
incantation?
```

## Jim
```
 Here is sample incantation that is current:
https://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2020/web/webtc/indexcaller.php?input=slp1&output=SktDevaUnicode&citation=sItA

The former parameters should continue to work -- 
let me know if you encounter exceptions.
Just the url part is different.
Compare this url to the one for 'MW B' (B=Basic)  on the home 
page:https://www.sanskrit-lexicon.uni-koeln.de/
```

## Dominik
```
Thank you, Jim.  Just right.

Is "Roman Unicode" in the plan for input?

```

## Jim
```
Currently Roman unicode is not recognized for input by most displays, in
particular by the indexcaller display program that I mentioned.  There is one display
 (see the 'Simple-Search' link on home page) which does recognize Roman Unicode (under the
name 'IAST').  It probably would be relatively simple to add 'IAST' as an input option to
the 'indexcaller' display.  How important would this enhancement be to you?
```

## Dominik
```
IAST is the standard Latin-script transliteration that has been used by 
indologists for over a century, maybe two.  Apart from Indian scripts, 
everything else is some kind of kludge (Kyoto-Harvard, CSX 
that I co-invented, REE) or aimed at niche programming tasks (SLP1). 
 Thirty years ago, it was quite hard to get computers to input or output accented 
characters outside the repertoire of German, Spanish and French.  
But today, since Unicode fonts, input and display systems are everywhere 
standard, there's no serious problem in using real Latin transliteration.  
rājā, kṛṣṇa, etc.    So it is my hope that eventually all these other stop-gap 
solutions (K-H, CSX, etc.) will fade away.  
There are no serious situations any more that require 7-bit data entry.  
(Maybe K-H for smartphones?)

So I would say that standard, scholarly Latin transliteration (IAST) should have a place 
beside Devanagari and other Indian scripts as an international standard.  All other 
systems are temporary and passing, in my view. 

I would dearly like IAST input.  And I think it would be good for all the dictionaries in 
the long term.
```



```

**Comment by gasyoun** [comment]
> So it is my hope that eventually all these other stop-gap solutions (K-H, CSX, etc.) will fade away.  

If Dominik, who is the godfather of quite a few of them, wants them to fade away - what else can we want our-self?

> I would dearly like IAST input. 

So do I. `Simple` everywhere.

**Comment by drdhaval2785** [comment]
I think this feature is now available in all dictionaries. A random search in the PW gave correct result with kṛta in https://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2020/web/webtc2/index.php. 
Am I getting it right, @funderburkjim ?

**Comment by funderburkjim** [comment]
I think this IAST/DEVA input option is available in all displays for all dictionaries.

Reason:  the script [redo_cologne_all.sh](https://github.com/sanskrit-lexicon/csl-websanlexicon/blob/master/v02/redo_cologne_all.sh) has been run from this repository on the cologne server.
This script installs the latest display code for all the dictionaries on the Cologne server.
