### ISSUE TITLE
Kill horizontal scroll

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/csl-websanlexicon#16]
@funderburkjim guess there is no real need to have such a scroll, it does not even fit my huge monitor.

![scroll](https://user-images.githubusercontent.com/80761/100007257-e00dfc00-2ddc-11eb-8607-a137e7642358.png)

**Comment by funderburkjim** [comment]
This is like the problem you noticed in https://github.com/funderburkjim/WhitneyGrammar/issues/1.

The solution there was to add css:
```
p,section {
 max-width:600px;
 text-align:justify;
 margin-right:10px;
}
```
I'll aim for a similar change to basic display.

**Comment by funderburkjim** [comment]
Changed [web/webtc/main.css](https://github.com/sanskrit-lexicon/csl-websanlexicon/blob/master/v02/makotemplates/web/webtc/main.css).

Now the  example above looks like:
![image](https://user-images.githubusercontent.com/6393033/100030139-d37baa80-2dc0-11eb-9262-94456d9d1f12.png)

**Comment by funderburkjim** [comment]
And if you narrow the browser window (even to an extremely narrow width), it still is reasonable, I think:
![image](https://user-images.githubusercontent.com/6393033/100030245-0c1b8400-2dc1-11eb-8beb-69c19d98c7b0.png)

**Comment by funderburkjim** [comment]
Currently, this change is present only for Lanman.

If others agree with the solution,  I'll apply to other dictionaries (such as MW).

**Comment by gasyoun** [comment]
> Currently, this change is present only for Lanman.

Very well looking.

> If others agree with the solution, I'll apply to other dictionaries (such as MW).

@drdhaval2785 ?

**Comment by drdhaval2785** [comment]
I am super dumb regarding frontend. Whatever suits Marcis may be done.

**Comment by funderburkjim** [comment]
@drdhaval2785 

The websanlexicon regeneration scripts currently include lanman.
And also the pywork regeneration scripts.
```
.../scans/csl-pywork/v02
> grep lan *.sh
redo_cologne_all.sh:sh generate_dict.sh lan  ../../LANScan/2020/
redo_xampp_all.sh:sh generate_dict.sh lan  ../../lan
> cd ../../csl-websanlexicon/v02
> grep lan *.sh
redo_cologne_all.sh:sh generate_web.sh lan  ../../LANScan/2020/
redo_xampp_all.sh:sh generate_web.sh lan  ../../lan
```

Let me know if lanman is missing somewhere else.

**Comment by funderburkjim** [comment]
The above solution to the 'long-line' problem is now installed for
displays for all dictionaries.
