### ISSUE TITLE
Browser title 

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-websanlexicon#17]
This issue expands upon a comment in [another issue](https://github.com/sanskrit-lexicon/csl-homepage/issues/4):
> Let's make the title not only good and short for a tab, but one that can be actually googled. LAN List is too esoteric. Lanman Sanskrit Reader Dictionary + year would make more sense.

## current situation
![image](https://user-images.githubusercontent.com/6393033/100487958-4e063c00-30d9-11eb-8093-9092539cd4f6.png)

The tab title is constructed as:  `<dictionary code> <display code>` .  For the list display of Lanman dictionary, this results in `LAN List`.

For the Advanced Search for MW this results in `MW Advanced`.  etc.

## template locations:
The tab title is specified in the template for the display. For instance, for Advanced Search,
in template file [web/webtc2/indexcaller.php](https://github.com/sanskrit-lexicon/csl-websanlexicon/blob/master/v02/makotemplates/web/webtc2/index.php):
`<title>${dictup} Advanced</title>`

and for List display, in template file [web/webtc1/index.php](https://github.com/sanskrit-lexicon/csl-websanlexicon/blob/master/v02/makotemplates/web/webtc1/index.php),
`<title>${dictup} List</title>`.

In these, `${dictup}` is a template variable resolved at code creation time by the table `alldictparms'
in [dictparms.py](https://github.com/sanskrit-lexicon/csl-websanlexicon/blob/master/v02/dictparms.py).

**Comment by funderburkjim** [comment]
## dictname 

The suggested improvement is probably close to t
the 'dictname' parameter in dictparms: 
```
  "dictname":u"Aufrecht Catalogus Catalogorum",
  "dictname":u"Apte Student's English-Sanskrit Dictionary",
  "dictname":u"Apte Practical Sanskrit-English Dictionary, revised edition, 1957",
  "dictname":u"Apte Practical Sanskrit-English Dictionary, 1890",
  "dictname":u"Benfey Sanskrit-English Dictionary",
  "dictname":u"Edgerton Buddhist Hybrid Sanskrit Dictionary",
  "dictname":u"Bopp Glossarium Sanscritum",
  "dictname":u"Borooah English-Sanskrit Dictionary",
  "dictname":u"Burnouf Dictionnaire Sanscrit-Français",
  "dictname":u"Cappeller Sanskrit-English Dictionary",
  "dictname":u"Cappeller Sanskrit Wörterbuch",
  "dictname":u"Grassman Wörterbuch zum Rig Veda",
  "dictname":u"Goldstücker Sanskrit-English Dictionary",
  "dictname":u"Indian Epigraphical Glossary",
  "dictname":u"Index to the Names in the Mahabharata",
  "dictname":u"Kṛdantarūpamālā",
  "dictname":u"Mehendale Mahabharata Cultural Index",
  "dictname":u"Macdonell Sanskrit-English Dictionary",
  "dictname":u"Monier-Williams Sanskrit-English Dictionary, 1899",
  "dictname":u"Monier-Williams Sanskrit-English Dictionary, 1872",
  "dictname":u"Monier-Williams English-Sanskrit Dictionary",
  "dictname":u"An Encyclopedic Dictionary of Sanskrit on Historical Principles",
  "dictname":u"Puranic Encyclopedia",
  "dictname":u"Personal and Geographical Names in the Gupta Inscriptions",
  "dictname":u"The Purana Index",
  "dictname":u"Böhtlingk Sanskrit-Wörterbuch in kürzerer Fassung",
  "dictname":u"Böhtlingk and Roth Grosses Petersburger Wörterbuch",
  "dictname":u"Schmidt Nachträge zum Sanskrit-Wörterbuch",
  "dictname":u"Shabda-Sagara Sanskrit-English Dictionary",
  "dictname":u"Sabda-kalpadruma",
  "dictname":u"Meulenbeld Sanskrit Names of Plants",
  "dictname":u"Stchoupak Dictionnaire Sanscrit-Français",
  "dictname":u"Vacaspatyam",
  "dictname":u"The Vedic Index of Names and Subjects",
  "dictname":u"Wilson Sanskrit-English Dictionary",
  "dictname":u"Yates Sanskrit-English Dictionary",
  "dictname":u"Lanman Sanskrit Reader Dictionary",
```

**Comment by funderburkjim** [comment]
## a new dicttitle parameter

The main problem with using `<dictname>`  instead of current `<dict code>` in the tab title is the
length of 'dictname' for some dictionaries, such as `Personal and Geographical Names in the Gupta Inscriptions`.

Here is a first approximation to dicttitles:
```
  "dicttitle":u"Aufrecht Catalogus Catalogorum",
  "dicttitle":u"Apte English-Sanskrit Dictionary",
  "dicttitle":u"Apte Sanskrit Dictionary 1957",
  "dicttitle":u"Apte Sanskrit Dictionary 1890",
  "dicttitle":u"Benfey Sanskrit Dictionary",
  "dicttitle":u"Edgerton Sanskrit Dictionary",
  "dicttitle":u"Bopp Glossarium Sanscritum",
  "dicttitle":u"Borooah English-Sanskrit Dictionary",
  "dicttitle":u"Burnouf Dictionnaire Sanscrit",
  "dicttitle":u"Cappeller Sanskrit Dictionary",
  "dicttitle":u"Cappeller Sanskrit Wörterbuch",
  "dicttitle":u"Grassman Wörterbuch",
  "dicttitle":u"Goldstücker Sanskrit Dictionary",
  "dicttitle":u"Indian Epigraphical Glossary",
  "dicttitle":u"Index to the Names in the Mahabharata",
  "dicttitle":u"Kṛdantarūpamālā",
  "dicttitle":u"Mahabharata Cultural Index",
  "dicttitle":u"Macdonell Sanskrit Dictionary",
  "dicttitle":u"Monier-Williams Sanskrit Dictionary 1899",
  "dicttitle":u"Monier-Williams Sanskrit Dictionary 1872",
  "dicttitle":u"Monier-Williams English-Sanskrit Dictionary",
  "dicttitle":u"Encyclopedic Dictionary of Sanskrit",
  "dicttitle":u"Puranic Encyclopedia",
  "dicttitle":u"Names in the Gupta Inscriptions",
  "dicttitle":u"The Purana Index",
  "dicttitle":u"Böhtlingk Sanskrit-Wörterbuch",
  "dicttitle":u"Böhtlingk and Roth  Wörterbuch",
  "dicttitle":u"Schmidt Nachträge zum Sanskrit-Wörterbuch",
  "dicttitle":u"Shabda-Sagara Sanskrit Dictionary",
  "dicttitle":u"Sabda-kalpadruma",
  "dicttitle":u"Meulenbeld Sanskrit Names of Plants",
  "dicttitle":u"Stchoupak Dictionnaire Sanscrit",
  "dicttitle":u"Vacaspatyam",
  "dicttitle":u"Vedic Index",
  "dicttitle":u"Wilson Sanskrit Dictionary",
  "dicttitle":u"Yates Sanskrit Dictionary",
  "dicttitle":u"Lanman Sanskrit Reader Dictionary",
```

**Comment by funderburkjim** [comment]
Some of those names still seem quite long for a browser tab.

Please provide better values.

**Comment by funderburkjim** [comment]
## Should the display code be in tab title

Currently, the tab title ends with a code for the display (e.g., Advanced, List, Basic, Mobile).

Should we keep that in a revision of the tab title?
For example, should it be `Wilson Sanskrit Dictionary` or `Wilson Sanskrit Dictionary Advanced`.

**Comment by gasyoun** [comment]
> Some of those names still seem quite long for a browser tab.

It's not critical. At least they will be found on Google.

> Should we keep that in a revision of the tab title?

Yes.

**Comment by gasyoun** [comment]
![list](https://user-images.githubusercontent.com/80761/101473533-fe3a3700-395a-11eb-8b25-49717ec4c68c.JPG)

Facebook preview is bad as bad is browser title as well.

**Comment by funderburkjim** [comment]
Have changed the browser 'title' according to table above.

There is some (probably temporary) problem with the Cologne server, so this change does
not show yet at Cologne.

Here's how it looks for MW advanced search, in local install.
![image](https://user-images.githubusercontent.com/6393033/101551052-65b5ae00-397e-11eb-8777-7cec8a65e49b.png)

**Comment by funderburkjim** [comment]
Changed browser title to 'Sanskrit simple search'.

**Comment by funderburkjim** [comment]
Year now added to browser title, per request by @gasyoun ([ref](https://github.com/sanskrit-lexicon/csl-websanlexicon/commit/8259041ab2b0e189740ded58d526166788750958#commitcomment-44937044))

**Comment by gasyoun** [comment]
> Year now added to browser title
I give you my thanks.
