### ISSUE TITLE
fonts directory

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-websanlexicon#2]
In #1, it was noted that for each dictionary, there is a web/fonts directory; and that these contain the same font files (with one exception VCPScan/2014 has praja.ttf file).

An appropriate place to manage the font files used by displays in dictionary web directories is here, in the csl-websanlexicon.

This issue devoted to setting up this management of web fonts.

**Comment by funderburkjim** [comment]
## font.css
Web font definitions are set up by css code in the webtc/font.css file; and only a few font files are mentioned:
```
# in csl-websanlexicon/v00/makotemplates directory
> grep -R '.[ot]tf'  *
webtc/font.css: src: url(../../web/fonts/praja.ttf);
webtc/font.css: src: url(../../web/fonts/sanskrit2003.ttf);
webtc/font.css: src: url(../../web/fonts/siddhanta.ttf);
webtc/font.css: src: url(../../web/fonts/oldstandard.otf);
webtc/font.css: src: url(../../web/fonts/oldstandarditalic.otf);
webtc/font.css: src: url(../../web/fonts/CharterIndoCapital.otf);
```

## v00/makotemplates/fonts  
MW has all 9 font files, so start fonts directory by copying
```
# current directory v00/makotemplates
cp -R ../../../MWScan/2014/web/fonts .
```
This gets us started with template files for fonts.  But some editing is desirable.

## remove praja font file
This is proprietary.  It should not be in this repository

## subdirectory for unmentioned font files
We *could* use these, but currently they are *not* even mentioned in font.css.
 So we'll put them in a separate place, for now.
There are 4 such files, and it seems ok to put them in a new makotemplates/fonts-unused folder.
This is done manually.
```
Old Standard Indologique-Italic.otf
Old Standard Indologique-Italic.ttf
Old Standard Indologique-Regular.otf
sanskrit2003.ttf   # this IS mentioned in font.css but is unused ... will be discussed further below
```

*to be continued tomorrow...*

**Comment by gasyoun** [comment]
> webtc/font.css: src: url(../../web/fonts/praja.ttf);
> webtc/font.css: src: url(../../web/fonts/sanskrit2003.ttf);
> webtc/font.css: src: url(../../web/fonts/siddhanta.ttf);

I would not delete not of them. But to have choice between three.

> webtc/font.css: src: url(../../web/fonts/oldstandard.otf);
> webtc/font.css: src: url(../../web/fonts/oldstandarditalic.otf);

So at least for Old Standard Indologique-Italic.ttf no need.

I do not remember for sure, but
Old Standard Indologique-Italic.otf
Old Standard Indologique-Regular.otf

could contain additional diacritics.

**Comment by funderburkjim** [comment]
> I would not delete not of them

Only praja is deleted, since it is proprietary.

The ones in fonts-unused are there for possible future use.

**Comment by gasyoun** [comment]
> Only praja is deleted, since it is proprietary.

So be it.

**Comment by funderburkjim** [comment]
## deletion action for generate.py

The [generate.py](https://github.com/sanskrit-lexicon/csl-websanlexicon/blob/master/v00/generate.py) program currently transfers files in [inventory.txt](https://github.com/sanskrit-lexicon/csl-websanlexicon/blob/master/v00/inventory.txt) to web folders of a specified dictionary. For example, for Grassman dictionary:
```
python generate.py gra inventory.txt  makotemplates ../../GRAScan/2014/web
```
Currently each file mentioned in the inventory.txt is classified as either:
* C = copy.  File is copied to Grassman 'web' directory. This is done by a Python system utility for copying files.  Example: `images/cologne_univ_seal.gif:C`
* T = template.  The file is used as a template and various adjustments made depending on the
     'gra' parameters.  The resulting adjusted text is then written to the Grassman 'web' directory.  Example: `webtc/indexcaller.php:T`

It is useful to add a 3rd possibility for files in inventory.txt:  deletion  (code = 'D').
For  example: `fonts/praja.ttf:D`.   The action would be:
* If the file is present in the Grassman 'web' directory, then  delete it.
* If the file is not present, do nothing.
   *  I think this type of operator is called a 'nilpotent' in configuration management tools like Chef,
       Ansible, etc.   This means that the result of doing the action twice (or many times) is the same as
       the result of doing the action just once.

**Comment by funderburkjim** [comment]
## Delete unused font files from web directories

This is accomplished by:
* modifying generate.py to Delete files 
* adding these five font files to inventory.txt for deletion
   ```
   fonts/praja.ttf:D
   fonts/Old Standard Indologique-Italic.otf:D
   fonts/Old Standard Indologique-Italic.ttf:D
   fonts/Old Standard Indologique-Regular.otf:D
   fonts/sanskrit2003.ttf:D
   ```
* We also add the 4 currently used font files to inventory.txt, with copy action:
   ```
   fonts/siddhanta.ttf:C
   fonts/CharterIndoCapital.otf:C
   fonts/oldstandard.otf:C
   fonts/oldstandarditalic.otf:C
   ```

Applying generate.py to all the dictionaries, via
`sh redo_cologne_all.sh`

**Comment by funderburkjim** [comment]
## Tidy praja and sanskrit2003 references

We can use `grep -R "praja" *` to find which template files mention `praja`. The files are:
webtc.font.css , webtc1/help/accents.html , webtc2/main.js

Similarly, `sanskrit2003` is mentioned in these template files:
webtc.font.css , webtc2/main.js

### Remove webtc/font.css references to praja and sanskrit2003: 
These are the lines removed:
```
@font-face { 
 src: url(../../web/fonts/praja.ttf);
 font-family: praja_deva;
}
.sdata_praja {
 color:teal;
 font-size:larger;
 font-family: praja_deva;
}
@font-face { 
 src: url(../../web/fonts/sanskrit2003.ttf);
 font-family: sanskrit2003_deva;
}
.sdata_sanskrit2003 {
 color:teal;
 font-size:larger;
 font-family: sanskrit2003_deva;
}
```

### Remove webtc2/main.js references to praja and sanskrit2003
These lines are in fact already in Javascript comments.  To clean up the file, these lines and some of the enclosing comments are removed.

**Comment by funderburkjim** [comment]
### Adjust webtc1/help/accents.html
This is part of some nice but underused documentation associated with the list display.

![image](https://user-images.githubusercontent.com/6393033/62168851-7a972180-b2f4-11e9-8695-fea972f2cac4.png)


This documentation actually needs to be updated.   The update could either
(a) Add a comment regarding the siddhanta web font, which displays the accents in the same 
     way as praja font
(b) Completely remove the mention of praja font, and replace with shorter comment regarding
     siddhanta.

A 'TODO' has been added to the [dokuwiki](https://www.sanskrit-lexicon.uni-koeln.de/doc/dokuwiki/doku.php?id=scans:csl-sanweblexicon) so maybe this will be attended to sometime.

**Comment by funderburkjim** [comment]
## install  changes for web directory of all dictionaries

in v00 directory at Cologne: `sh redo_cologne_all.sh`

I think this task is completed, and the csl-websanlexicon now manages the web/fonts directories in a satisfactory way.

**Comment by gasyoun** [comment]
Did not get why reference to sanskrit2003 was removed. Replaced by Siddhanta?

> (b) Completely remove the mention of praja font, and replace with shorter comment regarding
siddhanta.

Would be enough. Still could mention that Peter Freund's font Praja was used before.

**Comment by funderburkjim** [comment]
> Replaced by Siddhanta?

Yes -- Siddhanta is the font used for  Devanagari in the displays.  Since Sanskrit2003 not (currently) used,  no need to have it in the MWScan/2014/web/fonts, or in any of the fonts directories.

**Comment by gasyoun** [comment]
> Since Sanskrit2003 not (currently) used, no need to have it in the MWScan/2014/web/fonts, or in any of the fonts directories.

I would leave it, to become an option one day.
