### ISSUE TITLE
Links for Panini in MW

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-websanlexicon#22]
In #21, an approach was shown for getting links from Rg Veda and Atharva Veda references in MW to our custom-tailored repositories rvlinks and avlinks.
This was done by a change in the basicadjust.php component of the Cologne displays.

If this approach seems adequate,  we could use a similar approach to generate links for  Panini references in MW.  Here we would be starting with elements like `<ls>Pāṇ. 6-4, 107</ls>`.

I think @drdhaval2785 already has a candidate link target for such references (Dhaval -
  please remind me of details).

And the main task would be to convert  (in basicadjust.php) the
tag `<ls>Pāṇ. 6-4, 107</ls>` into an href  consistent with the candidate Panini reference.

We do not currently have an analogue to rvlinks/avlinks for Panini,  and perhaps we do not
require such, if Dhaval's candidate site suits our purpose.

**Comment by gasyoun** [comment]
> already has a candidate link target for such references

https://ashtadhyayi.com/dhatu/02.0004?form=%E0%A4%A6%E0%A5%8B%E0%A4%97%E0%A5%8D%E0%A4%A7%E0%A4%BF

**Comment by funderburkjim** [comment]
https://ashtadhyayi.com/sutraani/1/1/1  

This is probably the form that we can link to.

`<ls>Pāṇ. 6-4, 107</ls>`  => https://ashtadhyayi.com/sutraani/6/4/107

**Comment by drdhaval2785** [comment]
Yes.
https://ashtadhyayi.com/sutraani/1/1/1 is what I had in mind.

**Comment by funderburkjim** [comment]
## Pāṇ. link statistics
Examined mw.txt for references like `<ls>Pāṇ....</ls>`.
See [this gist](https://gist.github.com/funderburkjim/c3da3386cba90c3a15bbd8d4302e2f4d) for details.

8773 distinct such references were found, occurring in 8213 MW entries.

Of these, 
* 7998 marked Y. These instances are parseable into links, having form a-b,c as above example
* 95 marked N. These instances are not currently parseable into links; they need to be
   reviewed and some need correction so the links will be parseable.
* 680 instances marked with  X - these are non-specific references to Panini, for which no link should be expected.

**Comment by funderburkjim** [comment]
There is a systematic difference between the text in Panini links 
* as it appears in the digitization: `<ls>Pāṇ. 6-4, 107</ls>`
* as it appears in the text (headword 'ci', p. 394):
   ![image](https://user-images.githubusercontent.com/6393033/114278359-71cd7d00-99fd-11eb-8a41-131405469aef.png)

Don't know whether this difference is considered important enough to warrant attention.

**Comment by funderburkjim** [comment]
Went through the 95 'N' cases and made corrections to mw.txt for about 2/3 of them.

**Comment by funderburkjim** [comment]
Revised [basicadjust.php](https://github.com/sanskrit-lexicon/csl-websanlexicon/blob/master/v02/makotemplates/web/webtc/basicadjust.php) to generate links for Panini references as described above.  This revision now installed.

**Comment by gasyoun** [comment]
> Don't know whether this difference is considered important enough to warrant attention.

Until the links works I do not care, thanks - this was a long felt need, adding internal links to MW for the first time.

![fdsfsdfffsdfsd](https://user-images.githubusercontent.com/80761/114286175-13d48000-9a65-11eb-8e39-c7b27e711dea.png)

Just RV, AV and Panini do SO much magic, it's a dream.

**Comment by Andhrabharati** [comment]
> 
> 
> There is a systematic difference between the text in Panini links
> 
>     * as it appears in the digitization: `<ls>Pāṇ. 6-4, 107</ls>`
> 
>     * as it appears in the text (headword 'ci', p. 394):
>       ![image](https://user-images.githubusercontent.com/6393033/114278359-71cd7d00-99fd-11eb-8a41-131405469aef.png)
> 
> 
> Don't know whether this difference is considered important enough to warrant attention.

**This is exactly the one about which I was crying out, from the day I joined Cologne team.**
item (c) in https://github.com/sanskrit-lexicon/MWS/issues/95#issue-778886883
[Our policy at AB is to be close, as much possible, to the print text; except when there is a error/mistake in it- I had mentioned this in one of my posts earlier.]
