### ISSUE TITLE
Advanced Search highlighting Optional

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-websanlexicon#36]
A user (Odile) found that the highlighting in Advanced search display is annoying, and requested that the highlighting be made optional.
This issue describes the change made to address this request.

**Comment by funderburkjim** [comment]
Each session starts with the highlighting turned on, just as before.

<img width="650" alt="image" src="https://github.com/sanskrit-lexicon/csl-websanlexicon/assets/6393033/906717cd-eaac-49df-ac5b-936a0b9606a8">

**Comment by funderburkjim** [comment]
Switching to highlight off clears prior search, and hides the <=> navigation

<img width="641" alt="image" src="https://github.com/sanskrit-lexicon/csl-websanlexicon/assets/6393033/6ceb8d69-2609-4e2e-a3ac-67ad896c5e3e">

**Comment by funderburkjim** [comment]
Search results with `Highlight Off` :

<img width="640" alt="image" src="https://github.com/sanskrit-lexicon/csl-websanlexicon/assets/6393033/6480b408-a49f-4fd4-9f94-76b0d3022ec6">

**Comment by funderburkjim** [comment]
This seems a reasonable solution to me.
Will install this version for all dictionaries.

**Comment by gasyoun** [comment]
Well done, but people allready found it interesting at Auroville.
