### ISSUE TITLE
disp.php -> basicdisplay.php

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-websanlexicon#4]
The file currently named *webtc/disp.php* contains the class BasicDisplay.  As might be expected, this class is responsible for generating most of the HTML code for the Basic Display of the various dictionaries.  

In the apidev code (ref https://github.com/sanskrit-lexicon/csl-apidev/),  an exact copy of disp.php is renamed to a (more logical) *basicdisplay.php*.  

Several small changes are made to csl-websanlexicon to simplify naming.

**Comment by funderburkjim** [comment]
## rename disp.php

* in v00/makotemplates/webtc/:  `mv disp.php basicdisplay.php`
* change code references from disp.php to basicdisplay.php in
   * webtc/basicdisplay.php (3 places)
   * webtc/basicadjust.php  (only mentioned in 3 comments)
   * webtc/getwordviewmodel.php
   * webtc1/listhierview.php  (1 comment)
   * webtc1/main.js (1 comment)
   * webtc2/query_multi.php (1 use)

## Change documentation relative to csl-apidev.
 in readme_xampp.org,   down in the 'apidev' section,  the last instruction *was* to copy the
  csl-websanlexicon/v00/makotemplates/webtc/disp.php to apidev as *basicdisplay.php*.  
  Since we've changed the name of .../webtc/disp.php to .../webtc/basicdisplay.php,  we need to
  change the instruction in readme_xampp.org file to
``` 
cp ../csl-websanlexicon/v00/makotemplates/webtc/basicdisplay.php basicdisplay.php
```

## Change inventory.txt
* change `webtc/disp.php :T` to `webtc/basicdisplay.php:C`.     Note that the file actually has no template code,
  and should be considered a 'copy'-type file, rather than a template file.

**Comment by funderburkjim** [comment]
## Finish installation

### install in one dictionary and check
As a check, install for some dictionary (e.g. vcp), and check basic display and advanced search.
```
python generate.py vcp inventory.txt  makotemplates ../../VCPScan/2013/web
```
Displays look normal. Assume changes are good.

### Install for all dictionaries
In csl-websanlexicon/v00, run the installation script:
```
sh redo_cologne_all.sh
```

### double check MW
since the dictionary is used so often
👍

**Comment by funderburkjim** [comment]
## delete old copy of disp.php from webtc

The above steps leave one detail incomplete.   Namely, there is now a copy of disp.php in the 
web/webtc directory for each dictionary.  Since disp.php is an orphan (no program calls it any longer), it should be deleted.  Will do the necessary to fix this problem tomorrow.

**Comment by gasyoun** [comment]
Crystal clear documentation as usual.

**Comment by funderburkjim** [comment]
## finish deletion of disp.php

* add the file as a deletable item in [inventory.txt](https://github.com/sanskrit-lexicon/csl-websanlexicon/blob/master/v00/inventory.txt)
* install for mw, and double check displays work 
* install for all dictionaries: `sh redo_cologne_all.sh`


  * `webtc/disp.php:D`
