### ISSUE TITLE
Homonym repetition in pwg display

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-websanlexicon#41]
This issue fixes a bug present in the Cologne displays for pwg.

Here is how the bug looks in the Basic display.  

<img width="661" alt="image" src="https://github.com/sanskrit-lexicon/csl-websanlexicon/assets/6393033/e02e7e6c-7948-4248-b67c-c7cf0c960119">

It also occurs in the simple search display.

**Comment by funderburkjim** [comment]
A one-line change in basicadjust.php solves the problem for pwg in the basic, list, etc. displays.
Copying basicadjust.php to csl-apidev repo also fixes the bug in simple display.

Here's basic display as fixed:

<img width="575" alt="image" src="https://github.com/sanskrit-lexicon/csl-websanlexicon/assets/6393033/98191df5-f1d7-448e-9c17-c3184b7163e1">

**Comment by funderburkjim** [comment]
Currently, the '1.' and '2.' in pwg.txt are not marked with the hom tag.  If this tagging is done, then we would see these hom 
numbers in red, with a tooltip.

**Comment by Andhrabharati** [comment]
@funderburkjim 

As I had mentioned elsewhere (issue 68 in PWG), this issue is seen in some other dictionaries as well; for e.g. both the Cappeller's dictionaries have it.

So you need to add those all in the "array" in your code.

**Comment by funderburkjim** [comment]
## script to get dictionaries with `<h>`
```
dirorig='/c/xampp/htdocs/cologne/csl-orig/v02/'
for dictlo in  acc ae ap90 ben   bhs bop bor bur cae \
 ccs gra gst ieg inm  krm mci md mw mw72 \
 mwe pe pgn pui    pw pwg sch shs skd \
 snp stc vcp vei wil  yat lan armh
do
 xxx="$dirorig/$dictlo/$dictlo.txt"
 nh=`grep '<L>.*<h>' $xxx | wc -l`
 echo "$dictlo $nh"
done
```

------------

Output:

```
acc 0
ae 0
ap90 9
ben 0
bhs 94
bop 793
bor 0
bur 0
cae 2560
ccs 1796
gra 36
gst 25
ieg 0
inm 4298
krm 0
mci 319
md 920
mw 16443
mw72 3657
mwe 0
pe 2909
pgn 0
pui 7339
pw 0
pwg 6431
sch 0
shs 0
skd 0
snp 0
stc 1150
vcp 0
vei 314
wil 0
yat 0
lan 209
armh 0
```

**Comment by funderburkjim** [comment]
Additional dictionaries adjusted in display.
