### ISSUE TITLE
GRA display bug : abbrevs after chg

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-websanlexicon#42]
In discussion regarding a correction to Grassman digitization [here](https://github.com/sanskrit-lexicon/csl-orig/issues/1652#issuecomment-2205117984),  @Andhrabharati noticed a flaw in the Grassman display.

An abbreviation (marked in the usual  ways in gra.txt as `<ab>a.</ab>`) does not have the expected tooltip.

Further investigation suggests this happens at many places when an abbreviation follows a `<chg>` element.

For example, under hw adDA, with the 'u.s.w' abbreviation:

<img width="544" alt="image" src="https://github.com/sanskrit-lexicon/csl-websanlexicon/assets/6393033/07b46b58-701b-4fdb-9fe7-4793bf797a65">

**Comment by Andhrabharati** [comment]
Jim's [post](https://github.com/sanskrit-lexicon/csl-orig/issues/1736#issuecomment-2209498099) at csl-orig 1736 actually belongs and meant to be posted here.

**Comment by Andhrabharati** [comment]
And isn't this issue closeable now?

**Comment by funderburkjim** [comment]
basicadjust modification fixed the bug, for example:

<img width="451" alt="image" src="https://github.com/sanskrit-lexicon/csl-orig/assets/6393033/12cf5658-7ffb-48aa-a229-373527042619">

**Comment by funderburkjim** [comment]
Moved the mis-placed comment.  Thanks for mentioning.  
Closing this issue.
