### ISSUE TITLE
`<listinfo n="sup1"/>` markup in list display

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-websanlexicon#43]
Consider the list display for MW, with the headword 'apavarga':

There are two parts to the apavarga entries in the body of the text,
one is on column 1 of page 52 - and this is the one that is shown by
a search for apavarga:

<img width="800" alt="image" src="https://github.com/user-attachments/assets/3acd9da8-01e0-4108-81d0-4cde15b52dcd">

and the other is on column 2 of page 52; it is available by clicking on the yellow arrow 
above.

<img width="782" alt="image" src="https://github.com/user-attachments/assets/947255c0-d016-407c-a613-dd33bf2a6c60">

--------------------------------------------------------------------------
The red circle-S in the second image reflects the fact that there is some
material for apavarga from the supplement; this is confirmed in the display
by the red 'sup' in the right pane of the display.

However, in the first image, there is no circle-S in the left page.

This absence of circle-S in the left pane of the first image is viewed as a 
flaw [See discussion under "case 4:"](https://github.com/sanskrit-lexicon/csl-corrections/blob/master/app/correction_response/issue91/correction_response_20241105.txt).

**Comment by funderburkjim** [comment]
## A possible solution
* add `<listinfo n="sup1"/>` markup to the cdsl entry for the first apavarga (ID=9681).
* regenerate MW display using above revision to listhierview in this repo.

The result (from local display) is:

<img width="755" alt="image" src="https://github.com/user-attachments/assets/5c77fe6c-f5b2-4573-a572-486e59e353fb">

**Comment by funderburkjim** [comment]
If others confirm this solution, I'll promote it to Cologne server.

**Comment by Andhrabharati** [comment]
This appears good enough, Jim; and probably you may have to introduce the "rev1" markup as well, if the situation demands.

**Comment by Andhrabharati** [comment]
BTW, I had noticed that the homonyms are present only at some places, and not throughout (in the list window)?
[See "apavana" in the screen posted by you.]

Is there some reason behind this, or is that an exception or a flaw?

**Comment by funderburkjim** [comment]
I see homonym in left pane under apavana.   Where were you seeing 'not throughout'?

**Comment by funderburkjim** [comment]
> homonyms are present only at some places, and not throughout (in the list window)

@Andhrabharati   If you have some examples where the homonym is not present in the list window, please provide so I can track down the reason.

  Otherwise, this issue looks closeable.

**Comment by Andhrabharati** [comment]
You may close this issue for now, @funderburkjim!
