### ISSUE TITLE
xxxheader.xml 

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-websanlexicon#9]
## usage of xxxheader files

The xxxheader.xml files are shown by "License of Digital Edition" links on each dictionary's *home page*.  For example, for MW72:

![image](https://user-images.githubusercontent.com/6393033/68261862-5f346480-000f-11ea-8afe-ec9076d3e0d8.png)

While working on updating the  acknowledgments (see https://github.com/sanskrit-lexicon/GreekInSanskrit/issues/32) in these xxxheader files,  I noticed a few other aspects of these files that needed attention.

**Comment by funderburkjim** [comment]
## removal of duplicate

There were two independent copies of these xxxheader.xml files:
* csl-websanlexicon/v02/distinctfiles/xxx/web/xxxheader.xml
* csl-pywork/v02/distinctfiles/xxx/pywork/xxxheader.xml.

I removed the copies in csl-websanlexicon.
So, currently, there is only the one source, in csl-pywork/v02/distinctfiles, as indicated above.

`sh generate_dict.sh xxx ...` copies the csl-pywork copy of xxxheader.xml to xxx/pywork/xxxheader.xml.

It is convenient to have a second copy of the header file as xxx/web/xxxheader.xml ;
This web copy is made from the pywork copy as part of the pywork/redo_postxml.sh script.

**Comment by funderburkjim** [comment]
## csl-orig as source location for xxxheader.xml

It might be that the primary source location of these digital license files should be in the csl-orig
repository.  Namely:  csl-orig/v02/xxx/xxxheader.xml.  
The reason is that csl-orig/xxx/xxx.txt contains the basic form of the Cologne digitization of xxx.

Then, the generation process (script csl-pywork/v02/generate_dict.sh) could be altered to use 
the csl-orig version;  the csl-pywork/v02/distinctfiles/pywork/xxxheader.xml files would then be removed.

If others agree, I'll effect this change.

## xxx-meta2.txt also should be in csl-orig/xxx/

The xxx-meta2.txt  files are currently present as csl-pywork/v02/distinctfiles/pywork/xxx-meta2.txt.
For example, [mw72-meta2.txt](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/distinctfiles/mw72/pywork/mw72-meta2.txt).

These files contain some documentation of technical details regarding the digitization xxx.txt, 
sort of a 'readme' file for the digitization.

I propose that these meta files should also have their primary location in csl-orig:
csl-orig/v02/xxx/xxx-meta2.txt.

Do others agree?

**Comment by drdhaval2785** [comment]
I agree with both the proposals. Kindly effect the change.

**Comment by funderburkjim** [comment]
Good morning!  ok, will do.

**Comment by gasyoun** [comment]
> These files contain some documentation of technical details regarding the digitization xxx.txt,
sort of a 'readme' file for the digitization

Sure we agree, but if it's readme can't it be named a readme? :))

**Comment by funderburkjim** [comment]
xxx-meta2.txt and xxxheader.xml now based in csl-orig/v02.

I kind of like the mysterious nature of 'meta',  rather than the pedestrian 'readme' --  don't you?
